name: innervalley
services:
  mc:
    container_name: innervalley
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      MEMORY: "3G"
      VERSION: "1.21.3"
      TZ: "KST"
      DIFFICULTY: "hard"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
    restart: unless-stopped
    volumes:
      - /volume1/docker/innervalley-data:/data
  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        while true; do
          if [ "$$(date +%H%M)" = "0230" ]; then
            docker restart innervalley
          fi
          sleep 60
        done
  
